export const roleOptions = [
  {
    value: "creator",
    label: "Content Creator",
    description: "Create and schedule your own posts",
    icon: "✏️",
  },
  {
    value: "marketing",
    label: "Marketing Team",
    description: "Manage campaigns and team-wide content",
    icon: "📊",
  },
  {
    value: "business",
    label: "Business User",
    description: "Oversee accounts and business presence",
    icon: "💼",
  },
  {
    value: "admin",
    label: "Administrator",
    description: "Manage all users and platform settings",
    icon: "⚙️",
  },
];
export const roleConfig = {
  creator: {
    label: "Creator",
    badgeColor: "bg-brand-500 text-white",
    landingTitle: "My Content",
    landingDesc: "Manage your scheduled and draft posts.",
    primaryAction: "Create Post",
    navItems: [
      { name: "Dashboard", href: "/dashboard" },
      { name: "Campaigns", href: "/campaigns" },
      { name: "Analytics", href: "/analytics" },
      { name: "Reports", href: "/reports" },
      { name: "Create Post", href: "/posts/create" },
      { name: "Drafts", href: "/drafts" },
      { name: "Queue", href: "/queue" },
      { name: "Calendar", href: "/calendar" },
      { name: "Connected Accounts", href: "/social-accounts" },
      { name: "Profile", href: "/profile" },
    ],
  },
  marketing: {
    label: "Marketing",
    badgeColor: "bg-blue-500 text-white",
    landingTitle: "Team Content",
    landingDesc: "Overview of all team-wide scheduled content.",
    primaryAction: "Create Campaign",
    navItems: [
      { name: "Dashboard", href: "/dashboard" },
      { name: "Campaigns", href: "/campaigns" },
      { name: "Analytics", href: "/analytics" },
      { name: "Reports", href: "/reports" },
      { name: "Create Post", href: "/posts/create" },
      { name: "Drafts", href: "/drafts" },
      { name: "Queue", href: "/queue" },
      { name: "Calendar", href: "/calendar" },
      { name: "Connected Accounts", href: "/social-accounts" },
      { name: "Profile", href: "/profile" },
    ],
  },
  business: {
    label: "Business",
    badgeColor: "bg-green-500 text-white",
    landingTitle: "Account Overview",
    landingDesc: "Manage connected accounts and view summary.",
    primaryAction: "Connect Account",
    navItems: [
      { name: "Dashboard", href: "/dashboard" },
      { name: "Campaigns", href: "/campaigns" },
      { name: "Analytics", href: "/analytics" },
      { name: "Reports", href: "/reports" },
      { name: "Create Post", href: "/posts/create" },
      { name: "Drafts", href: "/drafts" },
      { name: "Queue", href: "/queue" },
      { name: "Calendar", href: "/calendar" },
      { name: "Connected Accounts", href: "/social-accounts" },
      { name: "Billing", href: "/billing" },
      { name: "Profile", href: "/profile" },
    ],
  },
  admin: {
    label: "Admin",
    badgeColor: "bg-red-500 text-white",
    landingTitle: "Platform Overview",
    landingDesc: "View all users and system activity.",
    primaryAction: "Manage Users",
    navItems: [
      { name: "Dashboard", href: "/dashboard" },
      { name: "Campaigns", href: "/campaigns" },
      { name: "Analytics", href: "/analytics" },
      { name: "Reports", href: "/reports" },
      { name: "Create Post", href: "/posts/create" },
      { name: "Drafts", href: "/drafts" },
      { name: "Queue", href: "/queue" },
      { name: "Calendar", href: "/calendar" },
      { name: "All Users", href: "/admin/users" },
      { name: "All Content", href: "/admin/content" },
      { name: "System Settings", href: "/settings" },
      { name: "Connected Accounts", href: "/social-accounts" },
      { name: "Profile", href: "/profile" },
    ],
  },
};
