// The 4 Core Roles for Registration & User Selection
export const roleOptions = [
  {
    value: "creator",
    label: "Content Creator",
    description: "Create, draft, and schedule your own posts",
    icon: "✏️",
  },
  {
    value: "marketing",
    label: "Marketing Team",
    description: "Manage marketing campaigns and cross-channel schedule",
    icon: "📊",
  },
  {
    value: "business",
    label: "Business User",
    description: "Oversee social accounts, billing plans, and business presence",
    icon: "💼",
  },
  {
    value: "admin",
    label: "Administrator",
    description: "Full platform administration, user oversight, and content moderation",
    icon: "🛡️",
  },
];

export const roleConfig = {
  creator: {
    label: "Creator",
    badgeColor: "bg-emerald-500 text-white",
    landingTitle: "Content Creator Studio",
    landingDesc: "Create compelling posts, rich media assets, drafts, and schedule personal content.",
    primaryAction: "Create Post",
    primaryHref: "/posts/create",
    navItems: [
      { name: "Dashboard", href: "/dashboard" },
      { name: "Create Post", href: "/posts/create" },
      { name: "Post Library", href: "/posts" },
      { name: "Drafts", href: "/drafts" },
      { name: "Publishing Queue", href: "/queue" },
      { name: "Calendar", href: "/calendar" },
      { name: "Connected Channels", href: "/social-accounts" },
      { name: "Profile", href: "/profile" },
    ],
    quickActions: [
      {
        label: "Create Post",
        href: "/posts/create",
        icon: "✏️",
        desc: "Draft or schedule new content",
      },
      {
        label: "My Drafts",
        href: "/drafts",
        icon: "📝",
        desc: "Review and edit saved drafts",
      },
      {
        label: "Publishing Queue",
        href: "/queue",
        icon: "📋",
        desc: "Manage scheduled timetable",
      },
      {
        label: "Interactive Calendar",
        href: "/calendar",
        icon: "📅",
        desc: "Visual schedule planner",
      },
    ],
  },
  marketing: {
    label: "Marketing",
    badgeColor: "bg-amber-500 text-white",
    landingTitle: "Marketing Operations",
    landingDesc: "Manage cross-channel campaigns, performance ROI, audience segments, and scheduled distributions.",
    primaryAction: "Create Campaign",
    primaryHref: "/campaigns",
    navItems: [
      { name: "Dashboard", href: "/dashboard" },
      { name: "Campaigns", href: "/campaigns" },
      { name: "Create Post", href: "/posts/create" },
      { name: "Post Library", href: "/posts" },
      { name: "Analytics & ROI", href: "/analytics" },
      { name: "Performance Reports", href: "/reports" },
      { name: "Calendar", href: "/calendar" },
      { name: "Publishing Queue", href: "/queue" },
      { name: "Connected Channels", href: "/social-accounts" },
      { name: "Profile", href: "/profile" },
    ],
    quickActions: [
      {
        label: "Campaign Hub",
        href: "/campaigns",
        icon: "🚀",
        desc: "Launch & track campaigns",
      },
      {
        label: "Performance Analytics",
        href: "/analytics",
        icon: "📊",
        desc: "Examine reach & engagement",
      },
      {
        label: "Executive Reports",
        href: "/reports",
        icon: "📑",
        desc: "Export PDF/CSV performance audits",
      },
      {
        label: "Schedule Pipeline",
        href: "/calendar",
        icon: "📅",
        desc: "Cross-channel content calendar",
      },
    ],
  },
  business: {
    label: "Business",
    badgeColor: "bg-blue-500 text-white",
    landingTitle: "Business Management",
    landingDesc: "Oversee connected social channels, team seats, billing subscriptions, and executive summaries.",
    primaryAction: "Connect Channel",
    primaryHref: "/social-accounts",
    navItems: [
      { name: "Dashboard", href: "/dashboard" },
      { name: "Connected Channels", href: "/social-accounts" },
      { name: "Billing & Plans", href: "/billing" },
      { name: "Executive Reports", href: "/reports" },
      { name: "Campaigns & ROI", href: "/campaigns" },
      { name: "Analytics", href: "/analytics" },
      { name: "Post Library", href: "/posts" },
      { name: "Profile", href: "/profile" },
    ],
    quickActions: [
      {
        label: "Connected Channels",
        href: "/social-accounts",
        icon: "🔗",
        desc: "Manage OAuth integrations",
      },
      {
        label: "Billing & Subscription",
        href: "/billing",
        icon: "💳",
        desc: "Manage seats & invoices",
      },
      {
        label: "Executive Reports",
        href: "/reports",
        icon: "📑",
        desc: "Download ROI summaries",
      },
      {
        label: "Campaign ROI",
        href: "/campaigns",
        icon: "📈",
        desc: "High-level marketing ROI",
      },
    ],
  },
  admin: {
    label: "Admin",
    badgeColor: "bg-purple-600 text-white",
    landingTitle: "System Administration & Governance",
    landingDesc: "Full administrative governance over registered users, content moderation, and platform settings.",
    primaryAction: "Manage Users",
    primaryHref: "/admin/users",
    navItems: [
      { name: "Dashboard", href: "/dashboard" },
      { name: "All Users", href: "/admin/users" },
      { name: "Content Moderation", href: "/admin/content" },
      { name: "System Health & Audit", href: "/admin/system-health" },
      { name: "Realtime Integrations Hub", href: "/admin/integrations" },
      { name: "Post Library", href: "/posts" },
      { name: "Create Post", href: "/posts/create" },
      { name: "Campaigns", href: "/campaigns" },
      { name: "Analytics", href: "/analytics" },
      { name: "Reports", href: "/reports" },
      { name: "Drafts", href: "/drafts" },
      { name: "Publishing Queue", href: "/queue" },
      { name: "Calendar", href: "/calendar" },
      { name: "Connected Channels", href: "/social-accounts" },
      { name: "Billing & Plans", href: "/billing" },
      { name: "System Settings", href: "/settings" },
      { name: "Profile", href: "/profile" },
    ],
    quickActions: [
      {
        label: "Realtime Integrations Hub",
        href: "/admin/integrations",
        icon: "⚡",
        desc: "Live ticklist audit & WebSockets",
      },
      {
        label: "User Management",
        href: "/admin/users",
        icon: "👥",
        desc: "Provision & manage accounts",
      },
      {
        label: "Content Moderation",
        href: "/admin/content",
        icon: "🛡️",
        desc: "Audit & moderate posts",
      },
      {
        label: "System Settings",
        href: "/settings",
        icon: "⚙️",
        desc: "Configure platform parameters",
      },
      {
        label: "Billing Overview",
        href: "/billing",
        icon: "💳",
        desc: "Monitor tenant subscription tiers",
      },
    ],
  },
};
